### ISSUE TITLE
Những tính năng cần phải bổ sung

### ISSUE THREAD

**Issue by nvn1176211** [passionstorm/hrm#36]
-Cho phép admin đặt setting cho công ty.
-Cho phép được đăng ký, đổi ca làm việc.
-Sửa lại cách người dùng thực hiện các hành động edit, delete sao cho phù hợp với giao diện mobile.
-Thêm những thể hiện(như checking...) cho người dùng biết hệ thống đang xử lý(áp dụng cho trường hợp đợi ajax response)

**Comment by minhvh93** [comment]
@nvn1176211  Mỗi cái issue là 1 task cụ thể chứ không gọp chung vậy. -> close issue này và log những issue con
