### ISSUE TITLE
Xóa những những folder hoặc file không cần thiết

### ISSUE THREAD

**Issue by minhvh93** [passionstorm/hrm#6]
- Hiện trạng: trong folder databases > migrate > ...  , và 1 số nới khác
- Mong muốn: Xóa những file không cần thiết để tránh gây hiểu nhầm khi chạy source

**Comment by nvn1176211** [comment]
đã xóa files trong databases > migrate

**Comment by minhvh93** [comment]
@nvn1176211  Fix xong thì tạo pull request đi

**Comment by nvn1176211** [comment]
thấy cái issues này ngắn nên merge luôn rồi

**Comment by nvn1176211** [comment]
merge với deploy cho issues #4 và #6 rồi

**Comment by minhvh93** [comment]
OK
